### ISSUE TITLE
Pretrained model on youtube vos dataset

### ISSUE THREAD

**Issue by tprdk** [anirudh-chakravarthy/ObjProp#1]
Thanks for your great work. Could you share the pretrained model for configuration 'masktrack_rcnn_r50_fpn_1x_youtubevos_objprop'?

**Comment by anirudh-chakravarthy** [comment]
Hi,

I have made the pre-trained weight available at the following [link](https://drive.google.com/file/d/17kFp60O0TOFjzO8jHSXKR4YzYUYefe-C/view?usp=sharing). I have also updated README with the Google Drive link.

**Comment by tprdk** [comment]
Hi,

Thanks for your reply. I really appreciate!
