### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by wangtao1996study** [anirudh-chakravarthy/ObjProp#2]
Excuse me.When i run the code,there is  an error:"ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn.src'".I find there is not a file named "deform_conv_cuda".But there are files named "deform_conv_cuda.cpp"and"deform_conv_cuda_kernel.cu".Can you help me please?

**Comment by anirudh-chakravarthy** [comment]
Hi,
Thanks for reaching out. You should try to install mmdetection. Specifically, can you try running the following:
```
python setup.py develop
# or "pip install -v -e .
```

I have also added these instructions to the README.
