### ISSUE TITLE
Issue while installing mmdetection

### ISSUE THREAD

**Issue by Allamrahul** [anirudh-chakravarthy/ObjProp#3]
Initially, I used python 3.7 with conda. I used the command provided in the repo to install pytorch. But when I tried installing mmdetection, it showed me that the min required version is python 3.8 while installing scipy.

But with python 3.8, I am unable to install pytorch. Could you let me know which python version you used?

**Comment by anirudh-chakravarthy** [comment]
Hi,

I used python 3.7 as well for installing mmdetection. On another project, I've successfully used `scipy==1.4.1 `with python3.7, can you try to see if that works for you?

**Comment by Allamrahul** [comment]
Thank you.
